### 1) Numpy Array


###### One of the features of Numpy is that it always tries to upcast the data in the array to the data having the largest datatype 

In [2]:
import numpy as np
np.array(["vividh",2,3])

array(['vividh', '2', '3'], dtype='<U6')

In [4]:
# Upcasting
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

###### 2-D Array (AKA Matrix)

In [5]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

###### By default numpy will calculate the dimensions of the array automatically but we can ovverride this and specify the dimensions of the data passed by mentioning it explicitly as below

In [8]:
np.array([[1,2],[2,4]],ndmin = 6)

array([[[[[[1, 2],
           [2, 4]]]]]])

###### we can also convert the dataype of the data passed into complex numbers

In [9]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

###### we can also pass in tuples inside the lists

In [10]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

###### We can explicitly link certain data to user defined datatypes 

In [17]:
# a is linked to '1' and <i2 is linked to 2
n = np.array([(1,2),(3,4)],dtype = [('a','<i2'),('b','<i8')])
# i2 means 16 bit
# i4 means 32 bit
#i8 means 64 bit

In [22]:
#checking their datatypes
type(n[1][0])

numpy.int16

###### Accessing data stored in 2D Arrays

In [14]:
# Accessing the 
x = np.array([(1,2),(3,4)])
x[0][0]

1

###### We can also convert the datatype to a matrix. Matrix is a subclass / subset of numpy array

In [23]:
np.mat(np.array([(1,2),(3,4)]))

matrix([[1, 2],
        [3, 4]])

In [27]:
#separate the data by semicolons
np.mat('1 2;3 4;5 7') 

matrix([[1, 2],
        [3, 4],
        [5, 7]])

### numpy.asarray()

###### It can convert your input into an array
###### Similar to np.array()

In [31]:
a = [[1,2,3],[4,5,6]]
type(a)
np.asarray(a)

array([[1, 2, 3],
       [4, 5, 6]])

##### We can even check if a function is  a subclass of any other fucntion

In [34]:
issubclass(np.array(),np.mat())

TypeError: Required argument 'object' (pos 1) not found

### numpy.asanyarray

##### It converts the data into array format if it is not already a subclass of array. 

In [39]:
a = np.mat([1,3])

In [40]:
np.array(a)

array([[1, 3]])

In [41]:
np.asarray(a)

array([[1, 3]])

In [43]:
# It isn't converted to array formate as matrix is already
# a subclass of array
np.asanyarray(a)

matrix([[1, 3]])

### np.copy()....a type of deep copy

##### Deep copy = creates a new space for the data
##### Shallow copy = only contains reference (pointers) to the original data

In [53]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [54]:
# This form of copying only references the actual location
# instead of making allocating new space to y. 
# Y and X are pointing to the same location
y = x 

In [55]:
# So if i make a change in Y, the change will be reflected
# in X as well...

y[1] = 213
x

array([  1, 213,   3,   4])

##### Now let's suppose you do not want the changes to be reflected in X, we can use the numpy.copy() function as follows

In [56]:
z = np.copy(x)
z[1] = 333

x #nothing changes this time!

array([  1, 213,   3,   4])

### numpy.fromfunction()

##### Allows us to construct an array by executing a function over each coordinate.

In [58]:
np.fromfunction(lambda i, j : i == j, (3,3),dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [59]:
np.fromfunction(lambda i, j : i * j, (3,3),dtype = int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [60]:
np.fromfunction(lambda i, j, k : i * j * k, (3,3, 3),dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

### numpy.fromiter()
##### Allows us to generate an array from an iterable (generator object)

In [62]:
iterabe = (x*x for x in range(5))
iterabe

<generator object <genexpr> at 0x000002075E00C830>

In [63]:
np.fromiter(iterabe,float)

array([ 0.,  1.,  4.,  9., 16.])

### numpy.fromstring()
###### Allows us to convert a string into an array

In [65]:
a = np.fromstring('1 2',dtype= int,sep =' ')
a

array([1, 2])

## numpy.arange() 

In [70]:
#python in-built range function does not take floating point
#numbers inside the range function
list(range(4,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

###### Numpy has function called arange() which will take floating point values as both step-size and the start-stop

In [72]:
np.arange(5,16,0.5) # Oof

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5])

## numpy.linspace()
###### it generates linearly spaced numbers in a specified range

In [75]:
#generates 50 data sequenctially which is linearly spaced
#between 1 and 5
np.linspace(1,5,50)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [89]:
np.linspace(1,2,2,retstep = True,endpoint = False)

(array([1. , 1.5]), 0.5)

## np.logspace()
###### just like linspace() it linearly separates the data and then finds out the log of the datapoints 

In [93]:
np.logspace(1,2,2,endpoint=False)

array([10.       , 31.6227766])

## np.zeros() and np.ones()
###### just as name implies it creates a matrix of specified dimensions and populates it with either 0'sor 1's

In [84]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [85]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

# Question 1:
### Create a (3,4,8) array with zeros and perform an addition operation with 5 and a multiplication operation with 2

In [94]:
(np.zeros((3,4,8))+5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

# Question 2:
### generate a array with [4,8,80]

In [102]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

# Question 3:
### Take any list, and convert it into matrix

In [97]:
list = [[1,2,3,4,5,5,6],[1,2,2,3,4,4,4]]
np.mat(list)

matrix([[1, 2, 3, 4, 5, 5, 6],
        [1, 2, 2, 3, 4, 4, 4]])

# Question 4:
### Create a (4,5,2) array with ones and output the dimensions,shape and datatype

In [99]:
n = np.ones((4,5,2))
print(n.ndim)
print(n.shape)
print(n.dtype)

3
(4, 5, 2)
float64


# Question 5:
### Create two arrays with dimensions (3,3,3) & (3,3,3) and do additions

In [100]:
x = np.ones((3,3,3))
y = np.ones((3,3,3))

In [101]:
x+y

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])